### ISSUE TITLE
compatibility with python 3

### ISSUE THREAD

**Issue by linnabraham** [isadoranun/FATS#7]
I cannot import FATS on python3.4 produces syntax error 

>>> import FATS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linn/.local/lib/python3.4/site-packages/FATS/__init__.py", line 2, in <module>
    from .Feature import FeatureSpace
  File "/home/linn/.local/lib/python3.4/site-packages/FATS/Feature.py", line 93
    print "Warning: the feature", name, "could not be calculated because", obj().Data, "are needed."
                               ^
SyntaxError: invalid syntax
>>>

**Comment by ryanjmccall** [comment]
@linnabraham the library is written in python2. see the old print function here: https://github.com/isadoranun/FATS/blob/master/FATS/Feature.py#L106   you could try setting up an virutalenv to run it using python2.

**Comment by kiranvarmas** [comment]
@ryanjmccall while we can import the FATS using python2 virtualenv, it may lead to backward compatibility issues , since arithmetic operators work differently in python3 when compared to python2. Is there any concrete solution other than creating a separate virtual env? Can't we use the **from __future__ import print_function** and change the print statements to functions in the existing code?

**Comment by stefanocovino** [comment]
Dear friends, 

if it helps, I'd support a real python3 version too!

  Stefano

**Comment by kiranvarmas** [comment]
I made changes to make it compatible with python 3. However didn't test it with the test cases as I was busy working on my project. If you are willing, we can collaborate in creating a python 3 version.

**Comment by stefanocovino** [comment]
Gladly.

Please, let me know what you think it could be useful to test.

Bye,
  Stefano




__________________

Mobilis in mobile

**Comment by kiranvarmas** [comment]
According to documentation, any changes made/introduced should pass the test cases specified . I have modified only part of the library to suffice my research. I can devote my time fully from May 1,2019.


Thanks,
Kiran Varma
________________________________

**Comment by OriginalGoku** [comment]
Was this issue resolved?

**Comment by stefanocovino** [comment]
Actually, I don't even remember having raised it. It might well have been solved, but I haven't worked on this code since then.

   Stefano
